// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"golang_api/models"
)

// DeleteUsersIDOKCode is the HTTP code returned for type DeleteUsersIDOK
const DeleteUsersIDOKCode int = 200

/*DeleteUsersIDOK OK

swagger:response deleteUsersIdOK
*/
type DeleteUsersIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.User `json:"body,omitempty"`
}

// NewDeleteUsersIDOK creates DeleteUsersIDOK with default headers values
func NewDeleteUsersIDOK() *DeleteUsersIDOK {

	return &DeleteUsersIDOK{}
}

// WithPayload adds the payload to the delete users Id o k response
func (o *DeleteUsersIDOK) WithPayload(payload *models.User) *DeleteUsersIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete users Id o k response
func (o *DeleteUsersIDOK) SetPayload(payload *models.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUsersIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteUsersIDUnauthorizedCode is the HTTP code returned for type DeleteUsersIDUnauthorized
const DeleteUsersIDUnauthorizedCode int = 401

/*DeleteUsersIDUnauthorized Unauthorized

swagger:response deleteUsersIdUnauthorized
*/
type DeleteUsersIDUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteUsersIDUnauthorized creates DeleteUsersIDUnauthorized with default headers values
func NewDeleteUsersIDUnauthorized() *DeleteUsersIDUnauthorized {

	return &DeleteUsersIDUnauthorized{}
}

// WithPayload adds the payload to the delete users Id unauthorized response
func (o *DeleteUsersIDUnauthorized) WithPayload(payload *models.Error) *DeleteUsersIDUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete users Id unauthorized response
func (o *DeleteUsersIDUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUsersIDUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteUsersIDNotFoundCode is the HTTP code returned for type DeleteUsersIDNotFound
const DeleteUsersIDNotFoundCode int = 404

/*DeleteUsersIDNotFound Not found

swagger:response deleteUsersIdNotFound
*/
type DeleteUsersIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteUsersIDNotFound creates DeleteUsersIDNotFound with default headers values
func NewDeleteUsersIDNotFound() *DeleteUsersIDNotFound {

	return &DeleteUsersIDNotFound{}
}

// WithPayload adds the payload to the delete users Id not found response
func (o *DeleteUsersIDNotFound) WithPayload(payload *models.Error) *DeleteUsersIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete users Id not found response
func (o *DeleteUsersIDNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteUsersIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
