// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"golang_api/models"
)

// PatchUsersIDOKCode is the HTTP code returned for type PatchUsersIDOK
const PatchUsersIDOKCode int = 200

/*PatchUsersIDOK OK

swagger:response patchUsersIdOK
*/
type PatchUsersIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.User `json:"body,omitempty"`
}

// NewPatchUsersIDOK creates PatchUsersIDOK with default headers values
func NewPatchUsersIDOK() *PatchUsersIDOK {

	return &PatchUsersIDOK{}
}

// WithPayload adds the payload to the patch users Id o k response
func (o *PatchUsersIDOK) WithPayload(payload *models.User) *PatchUsersIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch users Id o k response
func (o *PatchUsersIDOK) SetPayload(payload *models.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchUsersIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PatchUsersIDUnauthorizedCode is the HTTP code returned for type PatchUsersIDUnauthorized
const PatchUsersIDUnauthorizedCode int = 401

/*PatchUsersIDUnauthorized Unauthorized

swagger:response patchUsersIdUnauthorized
*/
type PatchUsersIDUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPatchUsersIDUnauthorized creates PatchUsersIDUnauthorized with default headers values
func NewPatchUsersIDUnauthorized() *PatchUsersIDUnauthorized {

	return &PatchUsersIDUnauthorized{}
}

// WithPayload adds the payload to the patch users Id unauthorized response
func (o *PatchUsersIDUnauthorized) WithPayload(payload *models.Error) *PatchUsersIDUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch users Id unauthorized response
func (o *PatchUsersIDUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchUsersIDUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PatchUsersIDNotFoundCode is the HTTP code returned for type PatchUsersIDNotFound
const PatchUsersIDNotFoundCode int = 404

/*PatchUsersIDNotFound User not found

swagger:response patchUsersIdNotFound
*/
type PatchUsersIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPatchUsersIDNotFound creates PatchUsersIDNotFound with default headers values
func NewPatchUsersIDNotFound() *PatchUsersIDNotFound {

	return &PatchUsersIDNotFound{}
}

// WithPayload adds the payload to the patch users Id not found response
func (o *PatchUsersIDNotFound) WithPayload(payload *models.Error) *PatchUsersIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch users Id not found response
func (o *PatchUsersIDNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchUsersIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
