// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"golang_api/models"
)

// PostUsersLoginOKCode is the HTTP code returned for type PostUsersLoginOK
const PostUsersLoginOKCode int = 200

/*PostUsersLoginOK OK

swagger:response postUsersLoginOK
*/
type PostUsersLoginOK struct {

	/*
	  In: Body
	*/
	Payload *models.LoginResponse `json:"body,omitempty"`
}

// NewPostUsersLoginOK creates PostUsersLoginOK with default headers values
func NewPostUsersLoginOK() *PostUsersLoginOK {

	return &PostUsersLoginOK{}
}

// WithPayload adds the payload to the post users login o k response
func (o *PostUsersLoginOK) WithPayload(payload *models.LoginResponse) *PostUsersLoginOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post users login o k response
func (o *PostUsersLoginOK) SetPayload(payload *models.LoginResponse) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUsersLoginOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostUsersLoginUnauthorizedCode is the HTTP code returned for type PostUsersLoginUnauthorized
const PostUsersLoginUnauthorizedCode int = 401

/*PostUsersLoginUnauthorized Unauthorized

swagger:response postUsersLoginUnauthorized
*/
type PostUsersLoginUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostUsersLoginUnauthorized creates PostUsersLoginUnauthorized with default headers values
func NewPostUsersLoginUnauthorized() *PostUsersLoginUnauthorized {

	return &PostUsersLoginUnauthorized{}
}

// WithPayload adds the payload to the post users login unauthorized response
func (o *PostUsersLoginUnauthorized) WithPayload(payload *models.Error) *PostUsersLoginUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post users login unauthorized response
func (o *PostUsersLoginUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUsersLoginUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
