// Code generated by go-swagger; DO NOT EDIT.

package users

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"golang_api/models"
)

// PostUsersCreatedCode is the HTTP code returned for type PostUsersCreated
const PostUsersCreatedCode int = 201

/*PostUsersCreated Created

swagger:response postUsersCreated
*/
type PostUsersCreated struct {

	/*
	  In: Body
	*/
	Payload *models.User `json:"body,omitempty"`
}

// NewPostUsersCreated creates PostUsersCreated with default headers values
func NewPostUsersCreated() *PostUsersCreated {

	return &PostUsersCreated{}
}

// WithPayload adds the payload to the post users created response
func (o *PostUsersCreated) WithPayload(payload *models.User) *PostUsersCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post users created response
func (o *PostUsersCreated) SetPayload(payload *models.User) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUsersCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostUsersUnauthorizedCode is the HTTP code returned for type PostUsersUnauthorized
const PostUsersUnauthorizedCode int = 401

/*PostUsersUnauthorized Unauthorized

swagger:response postUsersUnauthorized
*/
type PostUsersUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostUsersUnauthorized creates PostUsersUnauthorized with default headers values
func NewPostUsersUnauthorized() *PostUsersUnauthorized {

	return &PostUsersUnauthorized{}
}

// WithPayload adds the payload to the post users unauthorized response
func (o *PostUsersUnauthorized) WithPayload(payload *models.Error) *PostUsersUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post users unauthorized response
func (o *PostUsersUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUsersUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostUsersConflictCode is the HTTP code returned for type PostUsersConflict
const PostUsersConflictCode int = 409

/*PostUsersConflict A user already exists with this username or e-mail

swagger:response postUsersConflict
*/
type PostUsersConflict struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostUsersConflict creates PostUsersConflict with default headers values
func NewPostUsersConflict() *PostUsersConflict {

	return &PostUsersConflict{}
}

// WithPayload adds the payload to the post users conflict response
func (o *PostUsersConflict) WithPayload(payload *models.Error) *PostUsersConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post users conflict response
func (o *PostUsersConflict) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUsersConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostUsersUnprocessableEntityCode is the HTTP code returned for type PostUsersUnprocessableEntity
const PostUsersUnprocessableEntityCode int = 422

/*PostUsersUnprocessableEntity Unprocessable Entity (Usually when a required field is not there)

swagger:response postUsersUnprocessableEntity
*/
type PostUsersUnprocessableEntity struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostUsersUnprocessableEntity creates PostUsersUnprocessableEntity with default headers values
func NewPostUsersUnprocessableEntity() *PostUsersUnprocessableEntity {

	return &PostUsersUnprocessableEntity{}
}

// WithPayload adds the payload to the post users unprocessable entity response
func (o *PostUsersUnprocessableEntity) WithPayload(payload *models.Error) *PostUsersUnprocessableEntity {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post users unprocessable entity response
func (o *PostUsersUnprocessableEntity) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostUsersUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(422)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
