// Code generated by go-swagger; DO NOT EDIT.

// Package restapi Go-Lang API
//
//  Go-Lang API
//  Schemes:
//    http
//  Host: localhost:8000
//  BasePath: /v1
//  Version: 1.0.0
//  Contact: <email@hostname.com>
//
//  Consumes:
//    - application/json
//
//  Produces:
//    - application/json
//
// swagger:meta
package restapi
