// Code generated by go-swagger; DO NOT EDIT.

package books

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"golang_api/models"
)

// DeleteBooksIDOKCode is the HTTP code returned for type DeleteBooksIDOK
const DeleteBooksIDOKCode int = 200

/*DeleteBooksIDOK OK

swagger:response deleteBooksIdOK
*/
type DeleteBooksIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Book `json:"body,omitempty"`
}

// NewDeleteBooksIDOK creates DeleteBooksIDOK with default headers values
func NewDeleteBooksIDOK() *DeleteBooksIDOK {

	return &DeleteBooksIDOK{}
}

// WithPayload adds the payload to the delete books Id o k response
func (o *DeleteBooksIDOK) WithPayload(payload *models.Book) *DeleteBooksIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete books Id o k response
func (o *DeleteBooksIDOK) SetPayload(payload *models.Book) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteBooksIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteBooksIDUnauthorizedCode is the HTTP code returned for type DeleteBooksIDUnauthorized
const DeleteBooksIDUnauthorizedCode int = 401

/*DeleteBooksIDUnauthorized Unauthorized

swagger:response deleteBooksIdUnauthorized
*/
type DeleteBooksIDUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteBooksIDUnauthorized creates DeleteBooksIDUnauthorized with default headers values
func NewDeleteBooksIDUnauthorized() *DeleteBooksIDUnauthorized {

	return &DeleteBooksIDUnauthorized{}
}

// WithPayload adds the payload to the delete books Id unauthorized response
func (o *DeleteBooksIDUnauthorized) WithPayload(payload *models.Error) *DeleteBooksIDUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete books Id unauthorized response
func (o *DeleteBooksIDUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteBooksIDUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteBooksIDNotFoundCode is the HTTP code returned for type DeleteBooksIDNotFound
const DeleteBooksIDNotFoundCode int = 404

/*DeleteBooksIDNotFound Not found

swagger:response deleteBooksIdNotFound
*/
type DeleteBooksIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteBooksIDNotFound creates DeleteBooksIDNotFound with default headers values
func NewDeleteBooksIDNotFound() *DeleteBooksIDNotFound {

	return &DeleteBooksIDNotFound{}
}

// WithPayload adds the payload to the delete books Id not found response
func (o *DeleteBooksIDNotFound) WithPayload(payload *models.Error) *DeleteBooksIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete books Id not found response
func (o *DeleteBooksIDNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteBooksIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
