// Code generated by go-swagger; DO NOT EDIT.

package books

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"golang_api/models"
)

// GetBooksIDOKCode is the HTTP code returned for type GetBooksIDOK
const GetBooksIDOKCode int = 200

/*GetBooksIDOK OK

swagger:response getBooksIdOK
*/
type GetBooksIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Book `json:"body,omitempty"`
}

// NewGetBooksIDOK creates GetBooksIDOK with default headers values
func NewGetBooksIDOK() *GetBooksIDOK {

	return &GetBooksIDOK{}
}

// WithPayload adds the payload to the get books Id o k response
func (o *GetBooksIDOK) WithPayload(payload *models.Book) *GetBooksIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get books Id o k response
func (o *GetBooksIDOK) SetPayload(payload *models.Book) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBooksIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBooksIDUnauthorizedCode is the HTTP code returned for type GetBooksIDUnauthorized
const GetBooksIDUnauthorizedCode int = 401

/*GetBooksIDUnauthorized Unauthorized

swagger:response getBooksIdUnauthorized
*/
type GetBooksIDUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetBooksIDUnauthorized creates GetBooksIDUnauthorized with default headers values
func NewGetBooksIDUnauthorized() *GetBooksIDUnauthorized {

	return &GetBooksIDUnauthorized{}
}

// WithPayload adds the payload to the get books Id unauthorized response
func (o *GetBooksIDUnauthorized) WithPayload(payload *models.Error) *GetBooksIDUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get books Id unauthorized response
func (o *GetBooksIDUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBooksIDUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetBooksIDNotFoundCode is the HTTP code returned for type GetBooksIDNotFound
const GetBooksIDNotFoundCode int = 404

/*GetBooksIDNotFound Not found

swagger:response getBooksIdNotFound
*/
type GetBooksIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetBooksIDNotFound creates GetBooksIDNotFound with default headers values
func NewGetBooksIDNotFound() *GetBooksIDNotFound {

	return &GetBooksIDNotFound{}
}

// WithPayload adds the payload to the get books Id not found response
func (o *GetBooksIDNotFound) WithPayload(payload *models.Error) *GetBooksIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get books Id not found response
func (o *GetBooksIDNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetBooksIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
