// Code generated by go-swagger; DO NOT EDIT.

package books

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetBooksIDHandlerFunc turns a function with the right signature into a get books ID handler
type GetBooksIDHandlerFunc func(GetBooksIDParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetBooksIDHandlerFunc) Handle(params GetBooksIDParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetBooksIDHandler interface for that can handle valid get books ID params
type GetBooksIDHandler interface {
	Handle(GetBooksIDParams, interface{}) middleware.Responder
}

// NewGetBooksID creates a new http.Handler for the get books ID operation
func NewGetBooksID(ctx *middleware.Context, handler GetBooksIDHandler) *GetBooksID {
	return &GetBooksID{Context: ctx, Handler: handler}
}

/*GetBooksID swagger:route GET /books/{id} books getBooksId

GetBook by ID

GetBook by ID

*/
type GetBooksID struct {
	Context *middleware.Context
	Handler GetBooksIDHandler
}

func (o *GetBooksID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetBooksIDParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
