// Code generated by go-swagger; DO NOT EDIT.

package books

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"golang_api/models"
)

// PatchBooksIDOKCode is the HTTP code returned for type PatchBooksIDOK
const PatchBooksIDOKCode int = 200

/*PatchBooksIDOK OK

swagger:response patchBooksIdOK
*/
type PatchBooksIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Book `json:"body,omitempty"`
}

// NewPatchBooksIDOK creates PatchBooksIDOK with default headers values
func NewPatchBooksIDOK() *PatchBooksIDOK {

	return &PatchBooksIDOK{}
}

// WithPayload adds the payload to the patch books Id o k response
func (o *PatchBooksIDOK) WithPayload(payload *models.Book) *PatchBooksIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch books Id o k response
func (o *PatchBooksIDOK) SetPayload(payload *models.Book) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchBooksIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PatchBooksIDUnauthorizedCode is the HTTP code returned for type PatchBooksIDUnauthorized
const PatchBooksIDUnauthorizedCode int = 401

/*PatchBooksIDUnauthorized Unauthorized

swagger:response patchBooksIdUnauthorized
*/
type PatchBooksIDUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPatchBooksIDUnauthorized creates PatchBooksIDUnauthorized with default headers values
func NewPatchBooksIDUnauthorized() *PatchBooksIDUnauthorized {

	return &PatchBooksIDUnauthorized{}
}

// WithPayload adds the payload to the patch books Id unauthorized response
func (o *PatchBooksIDUnauthorized) WithPayload(payload *models.Error) *PatchBooksIDUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch books Id unauthorized response
func (o *PatchBooksIDUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchBooksIDUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PatchBooksIDNotFoundCode is the HTTP code returned for type PatchBooksIDNotFound
const PatchBooksIDNotFoundCode int = 404

/*PatchBooksIDNotFound User not found

swagger:response patchBooksIdNotFound
*/
type PatchBooksIDNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPatchBooksIDNotFound creates PatchBooksIDNotFound with default headers values
func NewPatchBooksIDNotFound() *PatchBooksIDNotFound {

	return &PatchBooksIDNotFound{}
}

// WithPayload adds the payload to the patch books Id not found response
func (o *PatchBooksIDNotFound) WithPayload(payload *models.Error) *PatchBooksIDNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the patch books Id not found response
func (o *PatchBooksIDNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PatchBooksIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
