// Code generated by go-swagger; DO NOT EDIT.

package books

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PatchBooksIDHandlerFunc turns a function with the right signature into a patch books ID handler
type PatchBooksIDHandlerFunc func(PatchBooksIDParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PatchBooksIDHandlerFunc) Handle(params PatchBooksIDParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PatchBooksIDHandler interface for that can handle valid patch books ID params
type PatchBooksIDHandler interface {
	Handle(PatchBooksIDParams, interface{}) middleware.Responder
}

// NewPatchBooksID creates a new http.Handler for the patch books ID operation
func NewPatchBooksID(ctx *middleware.Context, handler PatchBooksIDHandler) *PatchBooksID {
	return &PatchBooksID{Context: ctx, Handler: handler}
}

/*PatchBooksID swagger:route PATCH /books/{id} books patchBooksId

UpdateBook by ID

UpdateBook by ID

*/
type PatchBooksID struct {
	Context *middleware.Context
	Handler PatchBooksIDHandler
}

func (o *PatchBooksID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewPatchBooksIDParams()

	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		r = aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
