// Code generated by go-swagger; DO NOT EDIT.

package books

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"golang_api/models"
)

// PostBooksCreatedCode is the HTTP code returned for type PostBooksCreated
const PostBooksCreatedCode int = 201

/*PostBooksCreated Created

swagger:response postBooksCreated
*/
type PostBooksCreated struct {

	/*
	  In: Body
	*/
	Payload *models.Book `json:"body,omitempty"`
}

// NewPostBooksCreated creates PostBooksCreated with default headers values
func NewPostBooksCreated() *PostBooksCreated {

	return &PostBooksCreated{}
}

// WithPayload adds the payload to the post books created response
func (o *PostBooksCreated) WithPayload(payload *models.Book) *PostBooksCreated {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post books created response
func (o *PostBooksCreated) SetPayload(payload *models.Book) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostBooksCreated) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(201)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostBooksUnauthorizedCode is the HTTP code returned for type PostBooksUnauthorized
const PostBooksUnauthorizedCode int = 401

/*PostBooksUnauthorized Unauthorized

swagger:response postBooksUnauthorized
*/
type PostBooksUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostBooksUnauthorized creates PostBooksUnauthorized with default headers values
func NewPostBooksUnauthorized() *PostBooksUnauthorized {

	return &PostBooksUnauthorized{}
}

// WithPayload adds the payload to the post books unauthorized response
func (o *PostBooksUnauthorized) WithPayload(payload *models.Error) *PostBooksUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post books unauthorized response
func (o *PostBooksUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostBooksUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostBooksConflictCode is the HTTP code returned for type PostBooksConflict
const PostBooksConflictCode int = 409

/*PostBooksConflict A book already exists with this title and author

swagger:response postBooksConflict
*/
type PostBooksConflict struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostBooksConflict creates PostBooksConflict with default headers values
func NewPostBooksConflict() *PostBooksConflict {

	return &PostBooksConflict{}
}

// WithPayload adds the payload to the post books conflict response
func (o *PostBooksConflict) WithPayload(payload *models.Error) *PostBooksConflict {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post books conflict response
func (o *PostBooksConflict) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostBooksConflict) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(409)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostBooksUnprocessableEntityCode is the HTTP code returned for type PostBooksUnprocessableEntity
const PostBooksUnprocessableEntityCode int = 422

/*PostBooksUnprocessableEntity Unprocessable Entity (Usually when a required field is not there)

swagger:response postBooksUnprocessableEntity
*/
type PostBooksUnprocessableEntity struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostBooksUnprocessableEntity creates PostBooksUnprocessableEntity with default headers values
func NewPostBooksUnprocessableEntity() *PostBooksUnprocessableEntity {

	return &PostBooksUnprocessableEntity{}
}

// WithPayload adds the payload to the post books unprocessable entity response
func (o *PostBooksUnprocessableEntity) WithPayload(payload *models.Error) *PostBooksUnprocessableEntity {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post books unprocessable entity response
func (o *PostBooksUnprocessableEntity) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostBooksUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(422)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
