// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PatchBook PatchBook
//
// Optional fields used for the PATCH method
//
// swagger:model PatchBook
type PatchBook struct {

	// author
	Author string `json:"author,omitempty"`

	// isbn
	Isbn string `json:"isbn,omitempty"`

	// title
	Title string `json:"title,omitempty"`
}

// Validate validates this patch book
func (m *PatchBook) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PatchBook) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PatchBook) UnmarshalBinary(b []byte) error {
	var res PatchBook
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
